[package]
name = "test_type_script"
version = "0.1.0"
edition = "2021"

[dependencies]
swc = "0.282.3"
swc_common = "0.36.2"
swc_ecma_ast = "0.117.4"
swc_ecma_parser = "0.148.1"
swc_ecma_transforms_typescript = "0.194.2"
swc_ecma_visit = "0.103.3"

rquickjs = { version = "0.6.2", features = ["loader", "macro"] }
