name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      run: rustup update stable

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install TypeScript
      run: npm install -g typescript

    - name: Format
      run: cargo fmt -- --check

    - name: Lint
      run: cargo clippy -- -D warnings

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose